apiVersion: v1
kind: Service
metadata:
  name: backend
spec:
  selector:
    app: backend
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: kyleuniversities/quiztube-backend-app:latest
          env:
            - name: QUIZTUBE_DATABASE_FULL_HOST
              value: _QUIZTUBE_DATABASE_FULL_HOST
            - name: QUIZTUBE_DATABASE_USERNAME
              value: _QUIZTUBE_DATABASE_USERNAME
            - name: QUIZTUBE_DATABASE_PASSWORD
              value: _QUIZTUBE_DATABASE_PASSWORD
            - name: QUIZTUBE_AWS_BUCKET_PATH
              value: _QUIZTUBE_AWS_BUCKET_PATH
            - name: DEV_TOOLS_PROJECT_PATH
              value: _DEV_TOOLS_PROJECT_PATH
            - name: AWS_ACCESS_KEY_ID
              value: _AWS_ACCESS_KEY_ID
            - name: AWS_SECRET_ACCESS_KEY
              value: _AWS_SECRET_ACCESS_KEY
