apiVersion: v1
kind: Service
metadata:
  name: frontend
  annotations:
    external-dns.alpha.kubernetes.io/hostname: quiztube.io
spec:
  selector:
    app: frontend
  type: LoadBalancer
  ports:
    - name: http
      port: 80
      targetPort: 80
    - name: https
      port: 443
      targetPort: 443
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: kyleuniversities/quiztube-frontend-app:latest
          ports:
            - containerPort: 80
              name: http
            - containerPort: 443
              name: https
          env:
            - name: REACT_APP_API_FULL_HOST
              value: /api
            - name: TEST_KEY_1
              value: test-value-1
            - name: TEST_KEY_2
              value: test-value-2
